### ISSUE TITLE
[PE-D][Tester C] Incomplete error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T15-3/tp#76]
When editing a member, say I specify an invalid email and birthday, only the invalidity of the email is mentioned. Would be useful to let the user know that the birthday format is also invalid. 

This is a minor bug if your team is picky about this :)

![image.png](https://raw.githubusercontent.com/larainezo/ped/main/files/7ff3bfc0-7a37-49c4-9923-78394dec655c.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: larainezo/ped#7

**Comment by brennalaurentan** [comment]
Will not be fixing as this is a minor issue. Errors in the command are fed to the user one-at-a-time (that is, if the email is wrong, the email error will show up until the email is correct. Then, the error in the date will be shown). This was intentional, and our app is meant to feed errors one-at-a-time instead of all at once.
